# Change these first
owner: hspsh # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Homepage
    url: https://hsp.sh
  - name: Forum
    url: https://forum.hsp.sh
    icon: https://www.discourse.org/favicon.ico
  - name: Auth service
    url: https://auth.hsp.sh
  - name: Kto hakuje
    url: https://whois.at.hsp.sh

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hsp.sh
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: hsp.sh status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - name: Homepage
      url: https://hsp.sh
    - name: Forum
      url: https://forum.hsp.sh
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
